
###--------------------product ------------------
GET http://localhost:4000/product-api/products

###
POST  http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productName":"laptop",
    "price":"123456",
    "brand":"dell"
}


###  search by id
GET http://localhost:4000/product-api/products/697dd0cfb5592ea1586dad72

### update by id product

PUT http://localhost:4000/product-api/products/697dd0cfb5592ea1586dad72
Content-Type: application/json

{
    "productName":"laptop",
    "price":"123456",
    "brand":"apple"
}