GET http://localhost:4000/user-api/users 


### create user
POST  http://localhost:4000/user-api/users 
Content-Type: application/json

{
    "username":"guptha",
    "password":"366",
    "age":21
}

###  read by object id
GET http://localhost:4000/user-api/users/697dbe65d6d4b9a5cbf514c6

### update user  change vishnu age 21 to 17
PUT   http://localhost:4000/user-api/users/697dbe65d6d4b9a5cbf514c6
Content-Type: application/json

{
    "username":"vishnu",
    "password":"123456",
    "age":17
}

### delete user by id
DELETE http://localhost:4000/user-api/users/697dbe65d6d4b9a5cbf514c6

